# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
"""Class that handles the UI.  Running this uses the client with UI (running client.py runs with no UI)"""

from PyQt5 import QtCore, QtGui, QtWidgets
import client_ui_styling as style
import client
import threading


class ClientMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.text_viewer = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_viewer.setGeometry(QtCore.QRect(10, 0, 780, 500))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(16)
        self.text_viewer.setFont(font)
        self.text_viewer.setObjectName("text_viewer")
        self.text_viewer.setHtml(style.style_text_browser(messages=["Server Text Here"]))
        self.text_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.text_entry.setGeometry(QtCore.QRect(10, 510, 680, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(16)
        self.text_entry.setFont(font)
        self.text_entry.setText("")
        self.text_entry.setObjectName("text_entry")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(690, 510, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.connection_label = QtWidgets.QLabel(self.centralwidget)
        self.connection_label.setGeometry(QtCore.QRect(10, 540, 780, 15))
        self.connection_label.setObjectName("connection_label")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.setWindowTitle("ChatSocket")
        self.submit_button.setText("Submit")
        self.connection_label.setText("Connected to 255.255.255.255 as User")

    def update_connection_label(self, server: str, display_name: str):
        self.connection_label.setText(f"Connected to {server} as {display_name}")

    def get_text_entry(self) -> str:
        return self.text_entry.text()

    def update_text_browser(self, messages: list):
        self.text_viewer.setHtml(style.style_text_browser(messages))


def client_thread():
    """Thread that handles client interactions"""
    client.start()


def manage_ui():
    thread = threading.Thread(target=client_thread)
    thread.start()

    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_obj = ClientMainWindow()
    ui_obj.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    manage_ui()
